'use client'

import { useState } from "react";
import PostItem from "./post-item";

export default function MainPosts() {
  const [databasePosts, setDatabasePosts] = useState([
    "Esta é  uma mensagem Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusda.",
    "Esta é  uma mensagem Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam at placeat est, vel nam exercitationem earum dignissimos molestias laboriosam temporibus cum ipsum labore nesciunt ut debitis repellendus quas aliquid atque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempore ut, nemo ipsa neque omnis aliquid fugit alias architecto hic placeat distinctio sunt illo officia? Cum nam ipsa nihil labore eius! muito longa que deveria ser truncada com reticências para não ultrapassar o tamanho do contêiner. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    "Esta é  uma mensagem Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam at placeat est, vel nam exercitationem earum dignissimos molestias laboriosam temporibus cum ipsum labore nesciunt ut debitis repellendus quas aliquid atque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempore ut, nemo ipsa neque omnis aliquid fugit alias architecto hic placeat distinctio sunt illo officia? Cum nam ipsa nihil labore eius! muito longa que deveria ser truncada com reticências para não ultrapassar o tamanho do contêiner. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    "Esta é  uma mensagem Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam at placeat est, vel nam exercitationem earum dignissimos molestias laboriosam temporibus cum ipsum labore nesciunt ut debitis repellendus quas aliquid atque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempore ut, nemo ipsa neque omnis aliquid fugit alias architecto hic placeat distinctio sunt illo officia? Cum nam ipsa nihil labore eius! muito longa que deveria ser truncada com reticências para não ultrapassar o tamanho do contêiner. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    "Esta é  uma mensagem Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam at placeat est, vel nam exercitationem earum dignissimos molestias laboriosam temporibus cum ipsum labore nesciunt ut debitis repellendus quas aliquid atque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempore ut, nemo ipsa neque omnis aliquid fugit alias architecto hic placeat distinctio sunt illo officia? Cum nam ipsa nihil labore eius! muito longa que deveria ser truncada com reticências para não ultrapassar o tamanho do contêiner. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    "Esta é  uma mensagem Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam at placeat est, vel nam exercitationem earum dignissimos molestias laboriosam temporibus cum ipsum labore nesciunt ut debitis repellendus quas aliquid atque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempore ut, nemo ipsa neque omnis aliquid fugit alias architecto hic placeat distinctio sunt illo officia? Cum nam ipsa nihil labore eius! muito longa que deveria ser truncada com reticências para não ultrapassar o tamanho do contêiner. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    "Esta é  uma mensagem Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam at placeat est, vel nam exercitationem earum dignissimos molestias laboriosam temporibus cum ipsum labore nesciunt ut debitis repellendus quas aliquid atque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempore ut, nemo ipsa neque omnis aliquid fugit alias architecto hic placeat distinctio sunt illo officia? Cum nam ipsa nihil labore eius! muito longa que deveria ser truncada com reticências para não ultrapassar o tamanho do contêiner. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    "Esta é  uma mensagem Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam at placeat est, vel nam exercitationem earum dignissimos molestias laboriosam temporibus cum ipsum labore nesciunt ut debitis repellendus quas aliquid atque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempore ut, nemo ipsa neque omnis aliquid fugit alias architecto hic placeat distinctio sunt illo officia? Cum nam ipsa nihil labore eius! muito longa que deveria ser truncada com reticências para não ultrapassar o tamanho do contêiner. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    "Esta é  uma mensagem Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam at placeat est, vel nam exercitationem earum dignissimos molestias laboriosam temporibus cum ipsum labore nesciunt ut debitis repellendus quas aliquid atque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempore ut, nemo ipsa neque omnis aliquid fugit alias architecto hic placeat distinctio sunt illo officia? Cum nam ipsa nihil labore eius! muito longa que deveria ser truncada com reticências para não ultrapassar o tamanho do contêiner. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    "Esta é  uma mensagem Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam at placeat est, vel nam exercitationem earum dignissimos molestias laboriosam temporibus cum ipsum labore nesciunt ut debitis repellendus quas aliquid atque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempore ut, nemo ipsa neque omnis aliquid fugit alias architecto hic placeat distinctio sunt illo officia? Cum nam ipsa nihil labore eius! muito longa que deveria ser truncada com reticências para não ultrapassar o tamanho do contêiner. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    "Esta é  uma mensagem Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam at placeat est, vel nam exercitationem earum dignissimos molestias laboriosam temporibus cum ipsum labore nesciunt ut debitis repellendus quas aliquid atque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempore ut, nemo ipsa neque omnis aliquid fugit alias architecto hic placeat distinctio sunt illo officia? Cum nam ipsa nihil labore eius! muito longa que deveria ser truncada com reticências para não ultrapassar o tamanho do contêiner. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    "Esta é  uma mensagem Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam at placeat est, vel nam exercitationem earum dignissimos molestias laboriosam temporibus cum ipsum labore nesciunt ut debitis repellendus quas aliquid atque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempore ut, nemo ipsa neque omnis aliquid fugit alias architecto hic placeat distinctio sunt illo officia? Cum nam ipsa nihil labore eius! muito longa que deveria ser truncada com reticências para não ultrapassar o tamanho do contêiner. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  ]);

  return (
    <section className="w-full h-auto flex items-center justify-center py-16">
      <div className="w-full grid grid-cols-1 gap-6 px-16">
        {databasePosts.map((postData, index) => (
          <PostItem key={index} text={postData} />
        ))}
      </div>
    </section>
  );
}
